apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
  namespace: default
  labels:
    app: movie-info-service
spec:
  ports:
    -
      port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30000
  selector:
    app: movie-info
  type: NodePort